# Generated by Django 3.2 on 2021-04-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('synopsis', models.TextField()),
                ('cover', models.TextField()),
            ],
        ),
    ]
