# Generated by Django 3.1.7 on 2021-04-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('SF', 'Sci-Fi'), ('FA', 'Fantasy'), ('HO', 'Horror'), ('NF', 'Non-Fiction'), ('MY', 'Mystery'), ('HU', 'Humour'), ('TH', 'Thriller'), ('CH', "Children's"), ('HF', 'Historical Fiction'), ('SP', 'Spiritual'), ('RO', 'Romance'), ('ME', 'Memoir'), ('PO', 'Poetry'), ('WE', 'Western'), ('YA', 'Young Adult')], default='SF', max_length=2),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
