# Generated by Django 3.2 on 2021-04-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210415_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover',
            field=models.CharField(default='https://i.imgur.com/2WkT35M.jpg', max_length=200),
        ),
    ]
